### ISSUE TITLE
How to properly extend Settingslogic

### ISSUE THREAD

**Issue by pjmuller** [settingslogic/settingslogic#12]
Hi there,

I tried to extend Settingslogic in a multi tenant context where I have multiple company yml files. But I'm getting unstable behavior... Here is my example.

When doing `CompanyAbcConfig.user("test@foo.bar")` 99% of the time the `user` method is called however sometimes (mostly on production) I get `Settingslogic::MissingSetting: Missing setting 'user'`. When this error arises it is always for a couple hours in a row and then it stops.

``` ruby
class CompanyAbcConfig < Settingslogic
  source "#{Rails.root}/config/company_abc.yml"
  namespace (ENV['CONFIG_ENV'] || Rails.env)
  extend GeneralConfig
end

module GeneralConfig
  def user(email)
    User.where(email: email, company_id: self.company.id)
  end
end
```

``` yaml
development: &development
  company:
    id: 1
    name: "abc"

production:
  <<: *development
```

Any help?
